In [1]:
import pandas as pd
import numpy as np
import json
import re

In [2]:
listing_data = pd.read_csv(r"C:\Users\prith\Downloads\airbnb-data-pipeline\data\raw\listings.csv.gz")

In [3]:
print(listing_data.head().to_string())

     id                        listing_url       scrape_id last_scraped           source                                               name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         description  neighborhood_overview                                                                                               picture_url  host_id                                 host_url  host_profile_id                                          host_profile_url host_name  host_since  hosts_time_as_user_years  hosts_time_as_user_months  hosts_time_as_host_years  hosts_time_as_host_months host_location                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   host_about  host_response_time  host_response_rate  host_acceptance_rate host_is_superhost  host_thumbnail_url                                                                                               host_picture_url  host_neighbourhood  host_listings_count  host_total_listings_count  host_verifications host_has_profile_pic host_identity_verified  neighbourhood neighbourhood_cleansed neighbourhood_group_cleansed   latitude  longitude                property_type        room_type  accommodates  bathrooms  bathrooms_text  bedrooms  beds                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    amenities    price price_quote_checkin_date price_quote_checkout_date  price_quote_total_price  price_quote_price_per_night                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      price_quote_raw  minimum_nights  maximum_nights  minimum_minimum_nights  maximum_minimum_nights  minimum_maximum_nights  maximum_maximum_nights  minimum_nights_avg_ntm  maximum_nights_avg_ntm  calendar_updated has_availability  availability_30  availability_60  availability_90  availability_365 calendar_last_scraped  number_of_reviews  number_of_reviews_ltm  number_of_reviews_l30d  availability_eoy  number_of_reviews_ly  estimated_occupancy_l365d  estimated_revenue_l365d first_review last_review  review_scores_rating  review_scores_accuracy  review_scores_cleanliness  review_scores_checkin  review_scores_communication  review_scores_location  review_scores_value license  instant_bookable  calculated_host_listings_count  calculated_host_listings_count_entire_homes  calculated_host_listings_count_private_rooms  calculated_host_listings_count_shared_rooms  reviews_per_month
0  6848  https://www.airbnb.com/rooms/6848  20260414135910   2026-04-14  previous scrape                   Only 2 stops to Manhattan studio                                                                                                                                                                                                                                                                                                                                                                                        Comfortable studio apartment with super comfortable king size bed and  full kitchen and bathroom located in FABULOUS Williamsburg, Brooklyn.                    NaN                                 https://a0.muscache.com/pictures/e4f031a7-f146-40fd-98fd-b399a940c505.jpg    15991  https://www.airbnb.com/users/show/15991     1.462507e+18  https://www.airbnb.com/users/profile/1462506783043501110     Allen         NaN                      16.0                       11.0                      15.0                        3.0  New York, NY  We love to travel. When we travel we like to stay in a comfortable place that is clean, neat and sweet smelling, for a reasonable price. That's what we rent to you. We love city life but we also love outdoor adventures. We like keep up with all that's new and exciting around New York and we're happy to tell you where to find it. Want to hear the new young musicians that people are excited about or the promising new artists - we'll tell you about them. The best restaurants - ask us.\r\nWant to take a break from the city we'll tell you about wilderness canoeing on the Delaware river - just an hour and a half's drive. We can tell you where to find the great salt water fishing with clean beautiful waters just an hour away from the city or how to take a one day trip by bus to ski in Vermont.\r\n\r\n\r\nWHY WILLIAMSBURG?\r\n\r\nWilliamsburg is FABULOUS. It's fast growing and it's fast changing. It's hip. In the 1960's the new and exciting place where culture was blooming was Greenwich Village. In the 70's the SOHO neighborhood was where cheap industrial loft space were being turned into places where the adventurous could move to New York, live cheaply and make the new art, music, and culture. These days Williamsburg has that special chemistry of the New York that's constantly renewing itself.                 NaN                 NaN                   NaN                 t                 NaN         https://a0.muscache.com/im/users/15991/profile_pic/1259104907/original.jpg?aki_policy=profile_x_medium                 NaN                  1.0                        NaN                 NaN                    t                      t            NaN           Williamsburg                     Brooklyn  40.709350 -73.953420           Entire rental unit  Entire home/apt             3        NaN          1 bath       2.0   NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ["Microwave", "Wifi", "Hangers", "Essentials", "Stove", "Dishwasher", "Free street parking", "Dishes and silverware", "Smoke alarm", "Bed linens", "Iron", "Carbon monoxide alarm", "Heating", "Shampoo", "Kitchen", "TV", "Fire extinguisher", "Oven", "Hot water", "Cooking basics", "Coffee maker", "Refrigerator", "Washer", "Hair dryer", "Air conditioning", "Extra pillows and blankets"]  $117.27               2026-12-20                2027-01-19                  3518.00                       117.27                                                                                                                                        {"quote": {"taxes": null, "currency": "USD", "date_match": null, "service_fee": null, "total_price": "3518", "cleaning_fee": null, "is_available": true, "discount_amount": null, "price_per_night": "117.2666666666666666666666667", "nightly_subtotal": null, "discounted_subtotal": "3517.64", "raw_price_line_items": [{"amount": "3517.64", "item_type": "other", "description": "Average monthly price", "price_string": "$3,517.64"}, {"amount": "3517.64", "item_type": "discounted_subtotal", "description": "Price after discount", "price_string": "$3,517.64"}], "returned_checkin_date": null, "requested_checkin_date": "2026-12-20", "returned_checkout_date": null, "requested_checkout_date": "2027-01-19"}}            30.0           240.0                    30.0                    30.0                   240.0                   240.0                    30.0                   240.0               NaN                t                8                8                9               138            2026-04-14                197                      3                       0                35                     4                        180                  21109.0   2009-05-25  2025-11-17                  4.60                    4.60                       4.85                   4.85                         4.80                    4.69                 4.59     NaN               NaN                               1                                            1                                             0                                            0               0.96
1  6872  https://www.airbnb.com/rooms/6872  20260414135910   2026-04-14  previous scrape  Uptown Sanctuary w/ Private Bath (Month to Month)  This charming distancing-friendly month-to-month home away from home located in Historic Harlem, Uptown Sanctuary is ideal for lovers of travel, work-life balance, art, soulful living,  culture, and kindness.<br /><br />Spacious bedroom available (if you require more space, please inquiry about the master bedroom with its own ensuite bathroom or renting the whole place).<br /><br />➨ Minimum 30-day stay only, thank you for understanding!<br />➨ Additional fees apply for events and must be approved in advance.                    NaN     https://a0.muscache.com/pictures/miso/Hosting-6872/original/50573585-928d-4de4-8c3d-da27a5a2b179.jpeg    16104  https://www.airbnb.com/users/show/16104     1.462507e+18  https://www.airbnb.com/users/profile/1462506784874222530       Kae         NaN                      16.0                       11.0                      15.0                        3.0  New York, NY                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      A former life in fashion and wellness has left me well traveled and a lover of all things work-life balance and zen living.  I have great living chemistry with independent, considerate professional females who don't work from home.                 NaN                 NaN                   NaN                 f                 NaN  https://a0.muscache.com/im/pictures/user/d865acc2-3cba-4f03-bf38-c50819aad378.jpg?aki_policy=profile_x_medium                 NaN                  2.0                        NaN                 NaN                    t                      t            NaN            East Harlem                    Manhattan  40.801070 -73.942550        Private room in condo     Private room             1        NaN   1 shared bath       NaN   NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ["Long term stays allowed", "Elevator", "Fire extinguisher", "Washer", "Carbon monoxide alarm", "Wifi", "Hangers", "Essentials", "Heating", "Luggage dropoff allowed", "Kitchen", "Exterior security cameras on property", "Hot water", "Paid parking garage off premises", "Free street parking", "Host greets you", "Dryer", "Smoke alarm"]   $66.87               2026-04-21                2026-05-21                  2006.00                        66.87      {"quote": {"taxes": null, "currency": "USD", "date_match": null, "service_fee": null, "total_price": "2006.00", "cleaning_fee": null, "is_available": true, "discount_amount": "293.55", "price_per_night": "66.86666666666666666666666667", "nightly_subtotal": null, "discounted_subtotal": "2006.00", "raw_price_line_items": [{"amount": "2299.55", "item_type": "other", "description": "Average monthly price", "price_string": "$2,299.55"}, {"amount": "-293.55", "item_type": "discount_amount", "description": "Monthly stay discount", "price_string": "-$293.55"}, {"amount": "2006.00", "item_type": "discounted_subtotal", "description": "Price after discount", "price_string": "$2,006.00"}], "returned_checkin_date": null, "requested_checkin_date": "2026-04-21", "returned_checkout_date": null, "requested_checkout_date": "2026-05-21"}}            30.0           180.0                    30.0                    30.0                   180.0                   180.0                    30.0                   180.0               NaN                t               23               53               83                83            2026-04-14                  2                      1                       0                83                     1                         60                   4012.0   2022-06-05  2025-10-07                  5.00                    5.00                       5.00                   5.00                         5.00                    5.00                 5.00     NaN               NaN                               2                                            0                                             2                                            0               0.04

In [4]:
listing_data.shape

(35036, 90)

In [5]:
listing_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 35036 entries, 0 to 35035
Data columns (total 90 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            35036 non-null  int64
 1   listing_url                                   35036 non-null  str
 2   scrape_id                                     35036 non-null  int64
 3   last_scraped                                  35036 non-null  str
 4   source                                        35036 non-null  str
 5   name                                          35034 non-null  str
 6   description                                   33517 non-null  str
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   34901 non-null  str
 9   host_id                                       35036 non-null  int64
 10  host_url                                      35036 non-null  str
 11  host_profile_id                               34196 non-null  float64
 12  host_profile_url                              34132 non-null  str
 13  host_name                                     34201 non-null  str
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      34196 non-null  float64
 16  hosts_time_as_user_months                     34196 non-null  float64
 17  hosts_time_as_host_years                      34196 non-null  float64
 18  hosts_time_as_host_months                     34196 non-null  float64
 19  host_location                                 27029 non-null  str
 20  host_about                                    19647 non-null  str
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             34196 non-null  str
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              34196 non-null  str
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           34196 non-null  float64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          34195 non-null  str
 32  host_identity_verified                        34196 non-null  str
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        35036 non-null  str
 35  neighbourhood_group_cleansed                  35036 non-null  str
 36  latitude                                      35036 non-null  float64
 37  longitude                                     35036 non-null  float64
 38  property_type                                 35036 non-null  str
 39  room_type                                     35036 non-null  str
 40  accommodates                                  35036 non-null  int64
 41  bathrooms                                     3797 non-null   float64
 42  bathrooms_text                                34918 non-null  str
 43  bedrooms                                      22972 non-null  float64
 44  beds                                          3761 non-null   float64
 45  amenities                                     35036 non-null  str
 46  price                                         20693 non-null  str
 47  price_quote_checkin_date                      21921 non-null  str
 48  price_quote_checkout_date                     21921 non-null  str
 49  price_quote_total_price                       20693 non-null  float64
 50  price_quote_price_per_night                   20693 non-null  float64
 51  price_quote_raw                               21921 non-null  str
 52  minimum_nights                                35033 non-null  float64
 53  maximum_nights                                35033 non-null  float64
 54  minimum_minimum_nights                        35033 non-null  float64
 55  maximum_minimum_nights                        35033 non-null  float64
 56  minimum_maximum_nights                        35033 non-null  float64
 57  maximum_maximum_nights                        35033 non-null  float64
 58  minimum_nights_avg_ntm                        35036 non-null  float64
 59  maximum_nights_avg_ntm                        35036 non-null  float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              29409 non-null  str
 62  availability_30                               35036 non-null  int64
 63  availability_60                               35036 non-null  int64
 64  availability_90                               35036 non-null  int64
 65  availability_365                              35036 non-null  int64
 66  calendar_last_scraped                         35036 non-null  str
 67  number_of_reviews                             35036 non-null  int64
 68  number_of_reviews_ltm                         35036 non-null  int64
 69  number_of_reviews_l30d                        35036 non-null  int64
 70  availability_eoy                              35036 non-null  int64
 71  number_of_reviews_ly                          35036 non-null  int64
 72  estimated_occupancy_l365d                     35036 non-null  int64
 73  estimated_revenue_l365d                       20693 non-null  float64
 74  first_review                                  24542 non-null  str
 75  last_review                                   24542 non-null  str
 76  review_scores_rating                          24542 non-null  float64
 77  review_scores_accuracy                        24532 non-null  float64
 78  review_scores_cleanliness                     24541 non-null  float64
 79  review_scores_checkin                         24528 non-null  float64
 80  review_scores_communication                   24536 non-null  float64
 81  review_scores_location                        24525 non-null  float64
 82  review_scores_value                           24526 non-null  float64
 83  license                                       5062 non-null   str
 84  instant_bookable                              0 non-null      float64
 85  calculated_host_listings_count                35036 non-null  int64
 86  calculated_host_listings_count_entire_homes   35036 non-null  int64
 87  calculated_host_listings_count_private_rooms  35036 non-null  int64
 88  calculated_host_listings_count_shared_rooms   35036 non-null  int64
 89  reviews_per_month                             24542 non-null  float64
dtypes: float64(42), int64(18), str(30)
memory usage: 24.1 MB

In [6]:
listing_data.describe()

,id,scrape_id,neighborhood_overview,host_id,host_profile_id,host_since,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,3.503600e+04,3.503600e+04,0.0,3.503600e+04,3.419600e+04,0.0,34196.000000,34196.000000,34196.000000,34196.000000,...,24528.000000,24536.000000,24525.000000,24526.00000,0.0,35036.000000,35036.000000,35036.000000,35036.000000,24542.000000
mean,5.007097e+17,2.026041e+13,NaN,1.855502e+08,1.467166e+18,NaN,8.454264,5.587613,6.939554,5.417710,...,4.834390,4.818834,4.745455,4.63393,NaN,54.826008,46.960212,7.034935,0.073467,0.778935
std,5.815799e+17,3.906306e-03,NaN,2.041843e+08,1.219032e+16,NaN,3.719542,3.379174,3.679800,3.299007,...,0.382086,0.424163,0.396114,0.50263,NaN,194.285084,193.302536,30.893477,0.906802,1.818459
min,6.848000e+03,2.026041e+13,NaN,1.678000e+03,1.462506e+18,NaN,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,NaN,1.000000,0.000000,0.000000,0.000000,0.010000
25%,2.158128e+07,2.026041e+13,NaN,1.965853e+07,1.462878e+18,NaN,6.000000,3.000000,4.000000,3.000000,...,4.820000,4.820000,4.660000,4.52000,NaN,1.000000,0.000000,0.000000,0.000000,0.070000
50%,5.148317e+07,2.026041e+13,NaN,9.954958e+07,1.465524e+18,NaN,9.000000,6.000000,7.000000,5.000000,...,4.950000,4.960000,4.860000,4.76000,NaN,1.000000,1.000000,0.000000,0.000000,0.230000
75%,1.030399e+18,2.026041e+13,NaN,3.378483e+08,1.469275e+18,NaN,11.000000,9.000000,10.000000,8.000000,...,5.000000,5.000000,5.000000,4.94000,NaN,8.000000,2.000000,2.000000,0.000000,0.830000
max,1.654399e+18,2.026041e+13,NaN,7.545790e+08,1.649332e+18,NaN,17.000000,11.000000,15.000000,11.000000,...,5.000000,5.000000,5.000000,5.00000,NaN,1090.000000,1090.000000,230.000000,20.000000,116.800000

In [7]:
listing_data.duplicated().sum()

np.int64(0)

In [8]:
Null_percent = pd.DataFrame({
    'missing_percent': listing_data.isnull().mean() * 100
})

print(Null_percent.to_string())

                                              missing_percent
id                                                   0.000000
listing_url                                          0.000000
scrape_id                                            0.000000
last_scraped                                         0.000000
source                                               0.000000
name                                                 0.005708
description                                          4.335541
neighborhood_overview                              100.000000
picture_url                                          0.385318
host_id                                              0.000000
host_url                                             0.000000
host_profile_id                                      2.397534
host_profile_url                                     2.580203
host_name                                            2.383263
host_since                                         100.000000
hosts_time_as_user_years                             2.397534
hosts_time_as_user_months                            2.397534
hosts_time_as_host_years                             2.397534
hosts_time_as_host_months                            2.397534
host_location                                       22.853636
host_about                                          43.923393
host_response_time                                 100.000000
host_response_rate                                 100.000000
host_acceptance_rate                               100.000000
host_is_superhost                                    2.397534
host_thumbnail_url                                 100.000000
host_picture_url                                     2.397534
host_neighbourhood                                 100.000000
host_listings_count                                  2.397534
host_total_listings_count                          100.000000
host_verifications                                 100.000000
host_has_profile_pic                                 2.400388
host_identity_verified                               2.397534
neighbourhood                                      100.000000
neighbourhood_cleansed                               0.000000
neighbourhood_group_cleansed                         0.000000
latitude                                             0.000000
longitude                                            0.000000
property_type                                        0.000000
room_type                                            0.000000
accommodates                                         0.000000
bathrooms                                           89.162576
bathrooms_text                                       0.336796
bedrooms                                            34.433154
beds                                                89.265327
amenities                                            0.000000
price                                               40.937892
price_quote_checkin_date                            37.432926
price_quote_checkout_date                           37.432926
price_quote_total_price                             40.937892
price_quote_price_per_night                         40.937892
price_quote_raw                                     37.432926
minimum_nights                                       0.008563
maximum_nights                                       0.008563
minimum_minimum_nights                               0.008563
maximum_minimum_nights                               0.008563
minimum_maximum_nights                               0.008563
maximum_maximum_nights                               0.008563
minimum_nights_avg_ntm                               0.000000
maximum_nights_avg_ntm                               0.000000
calendar_updated                                   100.000000
has_availability                                    16.060623
availability_30                                      0.000000
availability_60                                      0.000000
availability_90                                      0.000000
availability_365                                     0.000000
calendar_last_scraped                                0.000000
number_of_reviews                                    0.000000
number_of_reviews_ltm                                0.000000
number_of_reviews_l30d                               0.000000
availability_eoy                                     0.000000
number_of_reviews_ly                                 0.000000
estimated_occupancy_l365d                            0.000000
estimated_revenue_l365d                             40.937892
first_review                                        29.952049
last_review                                         29.952049
review_scores_rating                                29.952049
review_scores_accuracy                              29.980591
review_scores_cleanliness                           29.954904
review_scores_checkin                               29.992008
review_scores_communication                         29.969175
review_scores_location                              30.000571
review_scores_value                                 29.997717
license                                             85.552004
instant_bookable                                   100.000000
calculated_host_listings_count                       0.000000
calculated_host_listings_count_entire_homes          0.000000
calculated_host_listings_count_private_rooms         0.000000
calculated_host_listings_count_shared_rooms          0.000000
reviews_per_month                                   29.952049

In [9]:
# Summary of the listing dataset

# - The DataFrame has 36445 rows and 85 columns
# - The data dont have any duplicate value, but it has Nan values.

# - Change datatypes = {
#                       has_availability (str <-> Boolean)
#                       host_has_profile_pic (str <-> Boolean)
#                       host_identity_verified (str <-> Boolean)
#                       host_is_superhost (str <-> Boolean)
#
#                       first_review (str <-> datetime)
#                       bathrooms_text (str <-> float)
#                       amenities (list <-> Json-like string)
#                       }

# - As we have to prepare the data to train a model that predicts Nightly price of a property
#   Therefore, we have to drop few columns

In [10]:
#Dropping columns
cols_to_drop = [
    # 100% null
    'neighborhood_overview', 'host_since', 'host_response_time',
    'host_response_rate', 'host_acceptance_rate', 'host_thumbnail_url',
    'host_neighbourhood', 'host_total_listings_count', 'host_verifications',
    'neighbourhood', 'calendar_updated', 'estimated_revenue_l365d',
    'instant_bookable',
    # URLs and IDs
    'listing_url', 'scrape_id', 'last_scraped', 'picture_url',
    'host_url', 'host_profile_id', 'host_profile_url',
    'host_picture_url', 'calendar_last_scraped',
    # free text
    'name', 'description', 'host_about', 'host_name',
    # high null + not recoverable
    'license', 'host_location',
]

listing_data = listing_data.drop(columns=cols_to_drop)

listing_data = listing_data.drop(columns=['beds'])

listing_data = listing_data.drop(columns=[
    'minimum_minimum_nights', 'maximum_minimum_nights',
    'minimum_maximum_nights', 'maximum_maximum_nights'
])

listing_data = listing_data.drop(columns=['source'])
print(listing_data.shape)

(35036, 56)

In [11]:
listing_data['bathrooms_text'].value_counts().head(20)

bathrooms_text
1 bath               17648
1 shared bath         7045
1 private bath        4133
2 baths               2435
1.5 baths              937
2 shared baths         860
1.5 shared baths       536
2.5 baths              319
3 baths                246
0 shared baths         223
0 baths                 99
3.5 baths               86
4 baths                 54
2.5 shared baths        52
Half-bath               48
3 shared baths          48
Private half-bath       28
Shared half-bath        27
4 shared baths          27
4.5 baths               21
Name: count, dtype: int64

In [12]:
#Changing Datatypes
bool_cols = ['has_availability', 'host_is_superhost', 'host_has_profile_pic', 'host_identity_verified']

for col in bool_cols:
    listing_data[col] = listing_data[col].str.strip().str.lower().map({'t': True, 'f': False})

listing_data['first_review'] = pd.to_datetime(listing_data['first_review'])
listing_data['last_review'] = pd.to_datetime(listing_data['last_review'])

#converting bathroom_text to float values
def parse_bathrooms(text):
    if pd.isna(text):
        return np.nan
    
    text = str(text).lower().strip()
    
    # half bath = 0.5
    if 'half' in text:
        return 0.5
    
    # extract the first number (handles 1, 1.5, 2 etc.)
    match = re.search(r'[\d.]+', text)
    if match:
        return float(match.group())
    
    return np.nan

listing_data['bathrooms_parsed'] = listing_data['bathrooms_text'].apply(parse_bathrooms)
listing_data = listing_data.drop(columns=['bathrooms'])
listing_data = listing_data.rename(columns={'bathrooms_parsed': 'bathrooms'})
listing_data = listing_data.drop(columns=['bathrooms_text'])
#placing bathroom_prased before bedrooms
cols = list(listing_data.columns)
cols.remove('bathrooms')
bedrooms_idx = cols.index('bedrooms')
cols.insert(bedrooms_idx, 'bathrooms')
listing_data = listing_data[cols]

In [13]:
listing_data = listing_data.drop(columns=['host_has_profile_pic', 'host_identity_verified'])

In [14]:
listing_data = listing_data.drop(columns=[
    'price_quote_checkin_date',
    'price_quote_checkout_date', 
    'price_quote_total_price',
    'price_quote_price_per_night',
    'price_quote_raw'
])

In [15]:
listing_data['price'] = listing_data['price'].str.replace('[$,]', '', regex=True).astype(float)

In [16]:
listing_data['price'].describe()

count    20693.000000
mean       254.998857
std        440.478328
min          4.470000
25%         93.800000
50%        167.250000
75%        279.500000
max      15075.000000
Name: price, dtype: float64

In [17]:
print(listing_data.head(10).to_string())

      id  host_id  hosts_time_as_user_years  hosts_time_as_user_months  hosts_time_as_host_years  hosts_time_as_host_months host_is_superhost  host_listings_count neighbourhood_cleansed neighbourhood_group_cleansed   latitude  longitude                property_type        room_type  accommodates  bathrooms  bedrooms                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    amenities   price  minimum_nights  maximum_nights  minimum_nights_avg_ntm  maximum_nights_avg_ntm has_availability  availability_30  availability_60  availability_90  availability_365  number_of_reviews  number_of_reviews_ltm  number_of_reviews_l30d  availability_eoy  number_of_reviews_ly  estimated_occupancy_l365d first_review last_review  review_scores_rating  review_scores_accuracy  review_scores_cleanliness  review_scores_checkin  review_scores_communication  review_scores_location  review_scores_value  calculated_host_listings_count  calculated_host_listings_count_entire_homes  calculated_host_listings_count_private_rooms  calculated_host_listings_count_shared_rooms  reviews_per_month
0   6848    15991                      16.0                       11.0                      15.0                        3.0              True                  1.0           Williamsburg                     Brooklyn  40.709350 -73.953420           Entire rental unit  Entire home/apt             3        1.0       2.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ["Microwave", "Wifi", "Hangers", "Essentials", "Stove", "Dishwasher", "Free street parking", "Dishes and silverware", "Smoke alarm", "Bed linens", "Iron", "Carbon monoxide alarm", "Heating", "Shampoo", "Kitchen", "TV", "Fire extinguisher", "Oven", "Hot water", "Cooking basics", "Coffee maker", "Refrigerator", "Washer", "Hair dryer", "Air conditioning", "Extra pillows and blankets"]  117.27            30.0           240.0                    30.0                   240.0             True                8                8                9               138                197                      3                       0                35                     4                        180   2009-05-25  2025-11-17                  4.60                    4.60                       4.85                   4.85                         4.80                    4.69                 4.59                               1                                            1                                             0                                            0               0.96
1   6872    16104                      16.0                       11.0                      15.0                        3.0             False                  2.0            East Harlem                    Manhattan  40.801070 -73.942550        Private room in condo     Private room             1        1.0       NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ["Long term stays allowed", "Elevator", "Fire extinguisher", "Washer", "Carbon monoxide alarm", "Wifi", "Hangers", "Essentials", "Heating", "Luggage dropoff allowed", "Kitchen", "Exterior security cameras on property", "Hot water", "Paid parking garage off premises", "Free street parking", "Host greets you", "Dryer", "Smoke alarm"]   66.87            30.0           180.0                    30.0                   180.0             True               23               53               83                83                  2                      1                       0                83                     1                         60   2022-06-05  2025-10-07                  5.00                    5.00                       5.00                   5.00                         5.00                    5.00                 5.00                               2                                            0                                             2                                            0               0.04
2   6990    16800                      16.0                       11.0                      15.0                        3.0              True                  1.0            East Harlem                    Manhattan  40.787780 -73.947590  Private room in rental unit     Private room             1        1.0       NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ["Wifi", "Hangers", "Room-darkening shades", "Stove", "Free street parking", "Smoke alarm", "Clothing storage", "Bed linens", "Iron", "Carbon monoxide alarm", "Heating", "Paid parking off premises", "Kitchen", "TV", "Fire extinguisher", "Hot water", "Coffee maker", "Refrigerator", "Hair dryer", "Air conditioning", "Extra pillows and blankets", "Host greets you"]   77.17            30.0           120.0                    30.0                   120.0             True                0                0                0               273                251                      3                       0               170                     3                        180   2009-10-28  2026-01-11                  4.88                    4.83                       4.95                   4.96                         4.94                    4.85                 4.84                               1                                            0                                             1                                            0               1.25
3   7097    17571                      16.0                       10.0                      15.0                        3.0              True                  2.0            Fort Greene                     Brooklyn  40.691940 -73.973890  Private room in guest suite     Private room             2        1.0       NaN                                                                                                                                                                                    ["Long term stays allowed", "Shower gel", "Microwave", "Outdoor dining area", "Dove Body Wash body soap", "Wifi", "Hangers", "Essentials", "Hot water kettle", "Toaster", "Books and reading material", "Free street parking", "Dishes and silverware", "Smoke alarm", "Bed linens", "Iron", "Carbon monoxide alarm", "Garden view", "Free dryer \u2013 In building", "Heating", "Luggage dropoff allowed", "Shampoo", "Cleaning products", "Kitchen", "Self check-in", "Central air conditioning", "Free washer \u2013 In building", "Private patio or balcony", "Outdoor furniture", "Fire extinguisher", "First aid kit", "Coffee", "Lockbox", "Wine glasses", "Hot water", "Dedicated workspace", "Paid parking garage off premises", "Cooking basics", "Coffee maker", "48 inch HDTV with Roku, standard cable", "Refrigerator", "Private entrance", "Shared backyard \u2013 Fully fenced", "Clothing storage: closet and dresser", "Hair dryer", "Extra pillows and blankets", "Ceiling fan", "Freezer", "Drying rack for clothing", "Mini fridge"]  202.47            30.0          1125.0                    30.0                  1125.0             True                0                0                0                45                423                     19                       0                 0                    28                        255   2010-01-16  2025-09-23                  4.89                    4.91                       4.89                   4.97                         4.93                    4.95                 4.82                               2                                            0                                             2                                            0               2.14
4   7801    21207                      16.0                       10.0                      15.0                        3.0              True                  3.0           Williamsburg                     Brooklyn  40.718807 -73.956177                 Entire place  Entire home/apt             2        1.0       NaN  ["Long term stays allowed", "Shower gel", "Microwave", "156 inch HDTV with Amazon Prime Video, Apple TV, HBO Max, Netflix", "Hangers", "Essentials", "Room-darkening shades", "Ethernet connection", "Dishwasher", "Hot water kettle", "Toaster", "Books and reading material", "Free street parking", "Clothing storage: wardrobe", "Free washer \u2013 In unit", "Conditioner", "Body soap", "Dishes and silverware", "Smoke alarm", "Whirlpool stainless steel gas stove", "Bed linens", "Iron", "Carbon monoxide alarm", "Heating", "Dining table", "Shampoo", "Cleaning products", "Kitchen", "Baking sheet", "Free dryer \u2013 In unit", "Fire extinguisher", "First aid kit", "Coffee", "Blender", "Wine glasses", "Private sauna", "Hot water", "Dedicated workspace", "Paid parking garage off premises", "Cooking basics", "Fast wifi \u2013 331 Mbps", "Coffee maker", "Cleaning available during stay", "Board games", "Refrigerator", "Shared backyard \u2013 Fully fenced", "Hair dryer", "Window AC unit", "Apple tv and Bose speakers sound system with Bluetooth and aux", "Record player", "Extra pillows and blankets", "Ceiling fan", "Stainless steel single oven", "Bathtub", "Drying rack for clothing", "Freezer"]  365.97            30.0           120.0                    30.0                   120.0             True                0                0               25               193                 13                      1                       1               136                     0                         60   2009-08-09  2026-03-29                  4.92                    4.80                       4.70                   4.90                         4.80                    5.00                 4.90                               1                                            1                                             0                                            0               0.06
5   8490    25183                      16.0                        9.0                      15.0                        3.0             False                  2.0     Bedford-Stuyvesant                     Brooklyn  40.684556 -73.939634                  Entire loft  Entire home/apt             5        1.0       1.0                                                                                                                                                                                                                                               ["BBQ grill", "Shower gel", "Microwave", "Outdoor dining area", "Long term stays allowed", "Wifi", "Hangers", "Essentials", "Room-darkening shades", "Hot water kettle", "Toaster", "Stainless steel gas stove", "Clothing storage: closet", "Laundromat nearby", "Books and reading material", "Free street parking", "Body soap", "Dishes and silverware", "Bed linens", "Iron", "Carbon monoxide alarm", "Children\u2019s books and toys", "Heating", "Dining table", "Shampoo", "Cleaning products", "Kitchen", "Luggage dropoff allowed", "Self check-in", "Baking sheet", "Barbecue utensils", "Private backyard \u2013 Fully fenced", "Private patio or balcony", "Rice maker", "Outdoor furniture", "First aid kit", "Oven", "Lockbox", "Wine glasses", "Hot water", "Cooking basics", "Coffee maker", "Board games", "Refrigerator", "Private entrance", "HDTV with standard cable", "Hair dryer", "Window AC unit", "Ceiling fan", "Bathtub", "Drying rack for clothing", "Freezer"]  193.03            30.0          1125.0                    30.0                  1125.0             True                7                8               14               208                189                      0                       0               105                     0                          0   2009-08-25  2023-10-16                  4.77                    4.83                       4.74                   4.88                         4.88                    4.67                 4.76                               2                                            2                                             0                                            0               0.93
6   9357    30193                      16.0                        8.0                      15.0                        3.0             False                  1.0         Hell's Kitchen                    Manhattan  40.767240 -73.986640           Entire rental unit  Entire home/apt             2        1.0       NaN                                                                                                                                                                                                                                                                                                                                                               ["Long term stays allowed", "Elevator", "Wifi", "Hangers", "Essentials", "Room-darkening shades", "Host greets you", "Ethernet connection", "Hot water kettle", "Toaster", "Paid dryer \u2013 In building", "Free street parking", "Body soap", "Dishes and silverware", "Pets allowed", "Smoke alarm", "Clothing storage", "Bed linens", "Iron", "Coffee maker: french press", "Carbon monoxide alarm", "Paid washer \u2013 In building", "Luggage dropoff allowed", "Shampoo", "Cleaning products", "Kitchen", "Gas stove", "Baking sheet", "Fire extinguisher", "First aid kit", "Single oven", "Coffee", "Radiant heating", "Wine glasses", "Exterior security cameras on property", "Hot water", "Paid parking garage off premises", "Cooking basics", "Refrigerator", "Hair dryer", "Window AC unit", "Extra pillows and blankets", "Ceiling fan", "Bathtub", "Freezer"]  104.35            30.0           120.0                    30.0                   120.0             True                0                0               12                80                 58                      0                       0                80                     0                          0   2009-10-04  2017-08-13                  4.52                    4.68                       4.16                   4.97                         5.00                    4.95                 4.58                               1                                            1                                             0                                            0               0.29
7  10452    35935                      16.0                        7.0                      15.0                        3.0              True                  6.0     Bedford-Stuyvesant                     Brooklyn  40.682940 -73.956820  Private room in rental unit     Private room             2        1.0       NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ["Long term stays allowed", "Microwave", "Wifi", "Hangers", "Essentials", "Room-darkening shades", "Stove", "Hot water kettle", "Toaster", "Laundromat nearby", "Free street parking", "Dishes and silverware", "Smoke alarm", "Bed linens", "Iron", "Carbon monoxide alarm", "Heating", "TV with Roku", "Dining table", "Shampoo", "Cleaning products", "Kitchen", "Free parking on premises", "Paid washer", "Baking sheet", "Oven", "Coffee", "Blender", "Hot water", "Dedicated workspace", "Cooking basics", "Paid dryer", "Coffee maker", "Cleaning available during stay", "Refrigerator", "Lock on bedroom door", "Hair dryer", "Air conditioning", "Extra pillows and blankets", "Freezer", "Drying rack for clothing"]   60.84            30.0           730.0                    30.0                   730.0             True                0                0               13               288                 82                      0                       0               185                     1                          0   2010-04-18  2025-03-31                  4.66                    4.50                       4.62                   4.74                         4.85                    4.42                 4.67                               6                                            0                                             6                                            0               0.42

In [18]:
Null_percent = pd.DataFrame({
    'missing_percent': listing_data.isnull().mean() * 100
})

print(Null_percent.to_string())

                                              missing_percent
id                                                   0.000000
host_id                                              0.000000
hosts_time_as_user_years                             2.397534
hosts_time_as_user_months                            2.397534
hosts_time_as_host_years                             2.397534
hosts_time_as_host_months                            2.397534
host_is_superhost                                    2.397534
host_listings_count                                  2.397534
neighbourhood_cleansed                               0.000000
neighbourhood_group_cleansed                         0.000000
latitude                                             0.000000
longitude                                            0.000000
property_type                                        0.000000
room_type                                            0.000000
accommodates                                         0.000000
bathrooms                                            0.336796
bedrooms                                            34.433154
amenities                                            0.000000
price                                               40.937892
minimum_nights                                       0.008563
maximum_nights                                       0.008563
minimum_nights_avg_ntm                               0.000000
maximum_nights_avg_ntm                               0.000000
has_availability                                    16.060623
availability_30                                      0.000000
availability_60                                      0.000000
availability_90                                      0.000000
availability_365                                     0.000000
number_of_reviews                                    0.000000
number_of_reviews_ltm                                0.000000
number_of_reviews_l30d                               0.000000
availability_eoy                                     0.000000
number_of_reviews_ly                                 0.000000
estimated_occupancy_l365d                            0.000000
first_review                                        29.952049
last_review                                         29.952049
review_scores_rating                                29.952049
review_scores_accuracy                              29.980591
review_scores_cleanliness                           29.954904
review_scores_checkin                               29.992008
review_scores_communication                         29.969175
review_scores_location                              30.000571
review_scores_value                                 29.997717
calculated_host_listings_count                       0.000000
calculated_host_listings_count_entire_homes          0.000000
calculated_host_listings_count_private_rooms         0.000000
calculated_host_listings_count_shared_rooms          0.000000
reviews_per_month                                   29.952049

In [19]:
# after seeing the null % summary again, we can see that only a few columns has significant null %
# therefore, for price - we have to drop the rows, as 40% is very high
#                bedrooms - fill it with median grouped by property_type
#                bathrooms -  fill it with median grouped by room_type
#                for all the host_time_as_user/host_years/month - fill it with median ()
#                for all the host_is_superhost - fill it with mode
#                has_availability - fill it with mode
#                first and last review - we can modify it to days_since_reviewed and fill the nan values with a large number
#                review scores_* -can't fill it with zero (as it means terrible listing), so will create has_reviews flag to preserve previous value and then fill null values with median
#                reviews_per_month - fill it with zero

In [20]:
#filling null values

listing_data = listing_data.dropna(subset=['price'])

host_numeric_column = ['hosts_time_as_user_years', 'hosts_time_as_user_months', 'hosts_time_as_host_years', 'hosts_time_as_host_months', 'host_listings_count']
for col in host_numeric_column:
    listing_data[col] = listing_data[col].fillna(listing_data[col].median())

listing_data['host_is_superhost'] = listing_data['host_is_superhost'].fillna(listing_data['host_is_superhost'].mode()[0])

listing_data['bathrooms'] = listing_data.groupby('room_type')['bathrooms'].transform(lambda x: x.fillna(x.median()))

listing_data['bedrooms'] = listing_data.groupby('property_type')['bedrooms'].transform(lambda x: x.fillna(x.median()))

listing_data['has_availability'] = listing_data['has_availability'].fillna(listing_data['has_availability'].mode()[0])

listing_data['reviews_per_month'] = listing_data['reviews_per_month'].fillna(0)

listing_data['has_reviews'] = listing_data['review_scores_rating'].notna().astype(int)
cols = list(listing_data.columns)
cols.remove('has_reviews')
rating_idx = cols.index('review_scores_rating')
cols.insert(rating_idx, 'has_reviews')
listing_data = listing_data[cols]

review_cols = ['review_scores_rating', 'review_scores_accuracy', 
               'review_scores_cleanliness', 'review_scores_checkin',
               'review_scores_communication', 'review_scores_location', 
               'review_scores_value']

for col in review_cols:
    listing_data[col] = listing_data[col].fillna(listing_data[col].median())

today = pd.Timestamp.today()

listing_data['days_since_first_review'] = (today - listing_data['first_review']).dt.days
listing_data['days_since_last_review'] = (today - listing_data['last_review']).dt.days

listing_data['days_since_first_review'] = listing_data['days_since_first_review'].fillna(99999)
listing_data['days_since_last_review'] = listing_data['days_since_last_review'].fillna(99999)

cols = list(listing_data.columns)
cols.remove('days_since_first_review')
cols.remove('days_since_last_review')
first_idx = cols.index('first_review')
cols.insert(first_idx, 'days_since_first_review')
cols.insert(first_idx + 1, 'days_since_last_review')
listing_data = listing_data[cols]

listing_data = listing_data.drop(columns=['first_review', 'last_review'])

In [21]:
Null_percent = pd.DataFrame({
    'missing_percent': listing_data.isnull().mean() * 100
})

print(Null_percent.to_string())

                                              missing_percent
id                                                   0.000000
host_id                                              0.000000
hosts_time_as_user_years                             0.000000
hosts_time_as_user_months                            0.000000
hosts_time_as_host_years                             0.000000
hosts_time_as_host_months                            0.000000
host_is_superhost                                    0.000000
host_listings_count                                  0.000000
neighbourhood_cleansed                               0.000000
neighbourhood_group_cleansed                         0.000000
latitude                                             0.000000
longitude                                            0.000000
property_type                                        0.000000
room_type                                            0.000000
accommodates                                         0.000000
bathrooms                                            0.000000
bedrooms                                             0.057991
amenities                                            0.000000
price                                                0.000000
minimum_nights                                       0.004833
maximum_nights                                       0.004833
minimum_nights_avg_ntm                               0.000000
maximum_nights_avg_ntm                               0.000000
has_availability                                     0.000000
availability_30                                      0.000000
availability_60                                      0.000000
availability_90                                      0.000000
availability_365                                     0.000000
number_of_reviews                                    0.000000
number_of_reviews_ltm                                0.000000
number_of_reviews_l30d                               0.000000
availability_eoy                                     0.000000
number_of_reviews_ly                                 0.000000
estimated_occupancy_l365d                            0.000000
days_since_first_review                              0.000000
days_since_last_review                               0.000000
has_reviews                                          0.000000
review_scores_rating                                 0.000000
review_scores_accuracy                               0.000000
review_scores_cleanliness                            0.000000
review_scores_checkin                                0.000000
review_scores_communication                          0.000000
review_scores_location                               0.000000
review_scores_value                                  0.000000
calculated_host_listings_count                       0.000000
calculated_host_listings_count_entire_homes          0.000000
calculated_host_listings_count_private_rooms         0.000000
calculated_host_listings_count_shared_rooms          0.000000
reviews_per_month                                    0.000000

In [22]:
#removing tiny remaining nulls from few columns 
listing_data = listing_data.dropna(subset=['bedrooms', 'minimum_nights', 'has_availability'])

In [23]:
Null_percent = pd.DataFrame({
    'missing_percent': listing_data.isnull().mean() * 100
})

print(Null_percent.to_string())

                                              missing_percent
id                                                        0.0
host_id                                                   0.0
hosts_time_as_user_years                                  0.0
hosts_time_as_user_months                                 0.0
hosts_time_as_host_years                                  0.0
hosts_time_as_host_months                                 0.0
host_is_superhost                                         0.0
host_listings_count                                       0.0
neighbourhood_cleansed                                    0.0
neighbourhood_group_cleansed                              0.0
latitude                                                  0.0
longitude                                                 0.0
property_type                                             0.0
room_type                                                 0.0
accommodates                                              0.0
bathrooms                                                 0.0
bedrooms                                                  0.0
amenities                                                 0.0
price                                                     0.0
minimum_nights                                            0.0
maximum_nights                                            0.0
minimum_nights_avg_ntm                                    0.0
maximum_nights_avg_ntm                                    0.0
has_availability                                          0.0
availability_30                                           0.0
availability_60                                           0.0
availability_90                                           0.0
availability_365                                          0.0
number_of_reviews                                         0.0
number_of_reviews_ltm                                     0.0
number_of_reviews_l30d                                    0.0
availability_eoy                                          0.0
number_of_reviews_ly                                      0.0
estimated_occupancy_l365d                                 0.0
days_since_first_review                                   0.0
days_since_last_review                                    0.0
has_reviews                                               0.0
review_scores_rating                                      0.0
review_scores_accuracy                                    0.0
review_scores_cleanliness                                 0.0
review_scores_checkin                                     0.0
review_scores_communication                               0.0
review_scores_location                                    0.0
review_scores_value                                       0.0
calculated_host_listings_count                            0.0
calculated_host_listings_count_entire_homes               0.0
calculated_host_listings_count_private_rooms              0.0
calculated_host_listings_count_shared_rooms               0.0
reviews_per_month                                         0.0

In [24]:
listing_data.shape

(20680, 49)

In [25]:
#modifying the amenities 
print(type(listing_data['amenities'][0]))
print(listing_data['amenities'][0])

<class 'str'>
["Microwave", "Wifi", "Hangers", "Essentials", "Stove", "Dishwasher", "Free street parking", "Dishes and silverware", "Smoke alarm", "Bed linens", "Iron", "Carbon monoxide alarm", "Heating", "Shampoo", "Kitchen", "TV", "Fire extinguisher", "Oven", "Hot water", "Cooking basics", "Coffee maker", "Refrigerator", "Washer", "Hair dryer", "Air conditioning", "Extra pillows and blankets"]

In [26]:
#prasing the whole column to actual lists
listing_data['amenities'] = listing_data['amenities'].apply(json.loads)

listing_data['amenity_count'] = listing_data['amenities'].apply(len)

In [27]:
listing_data['amenities'].explode().value_counts().head(20)

amenities
Smoke alarm              19555
Wifi                     19181
Carbon monoxide alarm    17713
Kitchen                  17065
Hot water                16004
Hangers                  15254
Essentials               14736
Hair dryer               14170
Iron                     14145
Air conditioning         14063
Bed linens               13969
Dishes and silverware    13397
Refrigerator             12887
Dedicated workspace      12611
Microwave                12387
Heating                  12331
Cooking basics           12300
TV                       11598
Shampoo                  10938
Fire extinguisher        10852
Name: count, dtype: int64

In [28]:
amen_counts = listing_data['amenities'].explode().value_counts()
wanted = ['Pool', 'Gym', 'Elevator', 'Parking', 'Washer', 'Dishwasher']
amen_counts.reindex(wanted, fill_value=0).sort_values(ascending=False)

amenities
Washer        5420
Dishwasher    5372
Elevator      4469
Gym           1865
Pool           249
Parking          0
Name: count, dtype: int64

In [29]:
top_amenities = ['Wifi', 'Kitchen', 'Air conditioning', 
                 'Dedicated workspace', 'TV', 'Heating', 
                 'Refrigerator', 'Microwave', 'Washer', 
                 'Dishwasher', 'Elevator', 'Gym']

for amenity in top_amenities:
    col_name = f"has_{amenity.lower().replace(' ', '_')}"
    listing_data[col_name] = listing_data['amenities'].apply(lambda x: 1 if amenity in x else 0)

In [30]:
has_cols = [c for c in listing_data.columns if c.startswith('has_')]
print(has_cols)
listing_data[has_cols].head()

['has_availability', 'has_reviews', 'has_wifi', 'has_kitchen', 'has_air_conditioning', 'has_dedicated_workspace', 'has_tv', 'has_heating', 'has_refrigerator', 'has_microwave', 'has_washer', 'has_dishwasher', 'has_elevator', 'has_gym']

,has_availability,has_reviews,has_wifi,has_kitchen,has_air_conditioning,has_dedicated_workspace,has_tv,has_heating,has_refrigerator,has_microwave,has_washer,has_dishwasher,has_elevator,has_gym
0,True,1,1,1,1,0,1,1,1,1,1,1,0,0
1,True,1,1,1,0,0,0,1,0,0,1,0,1,0
2,True,1,1,1,1,0,1,1,1,0,0,0,0,0
3,True,1,1,1,0,1,0,1,1,1,0,0,0,0
4,True,1,0,1,0,1,0,1,1,1,0,1,0,0

In [31]:
listing_data = listing_data.drop(columns=['amenities'])

In [32]:
#saving the cleaned file

listing_data.to_csv(r'C:\Users\prith\Downloads\airbnb-data-pipeline\data\processed\listing_clean.csv', index=False)
print(listing_data.shape)

(20680, 61)